site_name: Web Security
pages:
- [index.md, Home]
- ['content/XSS/Overview.md', 'XSS', 'XSS']
- ['content/XSS/XSS-Cookie.md', 'XSS', 'Stealing Cookie With XSS']
- ['content/XSS/Persistent-XSS.md', 'XSS', 'Persistent XSS']
- ['content/XSS/DOM-Based-XSS.md', 'XSS', 'DOM Based XSS']
- [help.md, Help]
- [about.md, About]
theme: united
repo_url: https://github.com/acgotaku/WebSecurity
copyright: Copyright &copy; 2015, <a href="https://github.com/acgotaku/WebSecurity">CSS WebSecurity</a>.